name: Deploy frontend to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies and build
      env:
        API_URL: "https://api.fair-enough.semanticscience.org"
      run: |
        git config --global user.email "vincent.emonet@gmail.com"
        git config --global user.name "Vincent Emonet"
        cd frontend
        yarn install
        yarn build

    - name: Deploy on GitHub
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: frontend/web-build
        CLEAN: true

    # - name: Deploy on GitHub
    #   run: yarn deploy